@startuml

[*] --> start

state "wdt_init" as start {
start: Инициализация сторожевого таймера.
}

start --> s1: 0

state "gpio_init" as s1 {
s1: Инициализация все используемых выводов.
s1: Подача тактового сигнала на порты, 
s1: выводы в которых инициализируется 
s1: будет подано автоматически.
}

@enduml