CLASS_NAME						=		AyPlayer
FILE_WITH_CLASS_DESCRIPTION		=		ayplayer.h

@startuml

[*] --> start

state "baseHardwareInit" as start {
start:Инициализация периферии, независящей от тактовой частоты:
start:1. Сторожевой таймер\t\t\t(WDT).
start:2. Порты ввода/вывода\t\t\t(GPIO).
}

@enduml