CLASS_NAME						=		AyPlayer
FILE_WITH_CLASS_DESCRIPTION		=		ayplayer.h
CAMELCASE						=		ON

@startuml

state "spiFailureHandler" as fspi {
fspi: SPI перестал работать.
fspi: Обработка исключительной 
fspi: ситуации.
fspi: С последующим выходом.
}

[*] --> s1 

state "guiInit" as s1 {
s1: Инициализация графической 
s1: оболочки.
}

s1 --> s2     : 0
s1 --> fspi   : 1

state "dpInit" as s2 {
s2: Инициализация цифровых
s2: потенциометров.
}

s2 --> fspi   : 2
s2 --> s3     : 0

state "furtherActions" as s3 {
s3: Какие-то дальнейшие действия
s3: После чего выход.
}

@enduml