#pragma once

enum class EC_BUTTON_NAME {
											UP_CLICK,
											DOWN_CLICK,
	LEFT_LONG_PRESS,	LEFT_LONG_CLICK,	LEFT_CLICK,
	RIGHT_LONG_PRESS,	RIGHT_LONG_CLICK,	RIGHT_CLICK,
	ENTER_LONG_PRESS,	ENTER_LONG_CLICK,	ENTER_CLICK,
											MENU_CLICK,
											BACK_CLICK,
};
